name: example
description: A CenterTheWidgets example app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  center_the_widgets:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
