name: center_the_widgets
description: Sometimes you want to deploy your mobile design-based app for large screens on the web or desktop, and you didn't write any code to make it responsive! CenterTheWidgets is developed to handle this for you.
version: 1.0.0+2
homepage: https://github.com/gabrimatic/center_the_widgets

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: