name: center_the_widgets
description: A simple widget that shows its child in the center of the screen. You can wrap any widget that you want to keep its size with CenterTheWidgets.
version: 1.0.0+1
homepage: https://github.com/gabrimatic/center_the_widgets

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: