name: center_the_widgets
description: A widget that shows it's chile in the center of the screen.
version: 1.0.0
homepage: https://github.com/gabrimatic/center_the_widgets

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: